project_id = "yueagxbvttykybkioywa"

[functions.send-staff-invitation]
verify_jwt = false

[functions.send-appointment-notification]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.send-backoffice-password-reset]
verify_jwt = false

[functions.verify-reset-token]
verify_jwt = false

[functions.complete-password-reset]
verify_jwt = false

[functions.complete-backoffice-password-reset]
verify_jwt = false

[functions.send-email-verification]
verify_jwt = false

[functions.submit-waitlist]
verify_jwt = false

[functions.create-public-booking]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.verify-backoffice-totp]
verify_jwt = false

[functions.backoffice-verify-step-up-totp]
verify_jwt = false

[functions.complete-password-change]
verify_jwt = false

[db.seed]
enabled = true
sql_paths = ['./seeds/*.sql']